---
- hosts: dev
  become: yes
  become_user: root
  pre_tasks:
    - include: pre_tasks/init.yml
  roles:

- hosts: prod
  become: yes
  become_user: root
  pre_tasks:
    - include: pre_tasks/init.yml
  roles:
    - ssh
